parameters:
#    vivait_settings.example.class: Vivait\SettingsBundle\Example

services:
#    vivait_settings.example:
#        class: %vivait_settings.example.class%
#        arguments: ["@service_id", "plain_value", %parameter%]

#  vivait_settings.expression_language:
#    class: Vivait\SettingsBundle\ExpressionLanguage
#    public: false

  # Repositories
  vivait_settings.repository.settings:
    class: Doctrine\ORM\EntityRepository
    factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
    arguments:
      - Vivait\SettingsBundle\Entity\Settings

  # Drivers
  vivait_settings.driver.yaml:
    class: Vivait\SettingsBundle\Driver\YamlDriver
    arguments: ["@service_container"]

  vivait_settings.driver.doctrine:
    class: Vivait\SettingsBundle\Driver\DoctrineDriver
    arguments: ["@doctrine.orm.default_entity_manager", "@vivait_settings.repository.settings"]

  # Registries
  vivait_settings.registry.drivers:
    class: Vivait\SettingsBundle\Services\DriversChain

  vivait_settings.registry.forms:
    class: Vivait\SettingsBundle\Services\FormChain

  vivait_settings.registry:
    class: Vivait\SettingsBundle\Services\SettingsChain
    arguments: ["@vivait_settings.registry.drivers", "@logger"]
    tags:
        - { name: monolog.logger, channel: vivait_settings }
